name: CML Ray Starter AMP
description: |
  Once all the tasks have completed, you can start a session to run the Ray Starter notebooks to get started with using Ray in CML
author: Vidushi Somani
specification_version: 1.0
prototype_version: 1.0
date: "2024-02-13"

runtimes:
  - editor: JupyterLab
    kernel: Python 3.10
    edition: Standard

tasks:
  - type: run_session
    name: Install Dependencies
    script: 1_session-install-deps/install_deps.py
    short_summary: Install Dependencies
    kernel: python3
    cpu: 2
    memory: 4
  
  - type: create_job
    name: Setup
    entity_label: setup
    script: 2_job-setup/setup.py
    arguments: None
    short_summary: Create job to setup runtimes for project 
    cpu: 2
    memory: 4
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: run_job
    entity_label: setup
    short_summary: Run job to setup runtimes for project
